### ISSUE TITLE
Remove K8S_HELM_VERSION_1_7 from Dockerfile

### ISSUE THREAD

**Issue by yenicapotediaz** [samsung-cnct/k2-tools#101]
Helm 2.5.1 does not fully support k8s 1.7, and should be removed.
Helm release notes:
`Helm v2.5.1 is tested on Kubernetes 1.5-1.7. However, the latest Kubernetes 1.7 features (e.g. custom type definitions) are not supported in this release. Full Kubernetes 1.7 support is coming in Helm 2.6`

**Comment by yenicapotediaz** [comment]
Blocked by https://github.com/samsung-cnct/k2/issues/513

**Comment by yenicapotediaz** [comment]
PR: https://github.com/samsung-cnct/k2-tools/pull/102

**Comment by leahnp** [comment]
LGTM
