### ISSUE TITLE
move build from quay.io to local jenkins instance

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-tools#18]
we should be building all of our artifacts to grow our experience and ensure we are able to move our artifact generation when we want to.

we will need to create a makefile and a jenkins job for this artifact.  we should continue to publish to quay.io

**Comment by coffeepac** [comment]
blocked by samsung-cnct/k2#189

**Comment by joejulian** [comment]
Is this different from #16?

**Comment by coffeepac** [comment]
I really liked this issue.
