### ISSUE TITLE
include three versions of kubectl

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-tools#23]
as part of samsung-cnct/k2#222 we are now supporting three minor versions of kubernetes.  to support this effort, this image will need to have three versions of kubectl installed at the following locations:

```
/opt/cnct/kubernetes/v1.4/bin/kubectl
/opt/cnct/kubernetes/v1.5/bin/kubectl
/opt/cnct/kubernetes/v1.6/bin/kubectl
```

We will always use a specific patch level at each minor version of kubernetes.  however, to make the usage of these binaries straightforward we will not include the patch level in the path.

**Comment by coffeepac** [comment]
for backwards compatibility, the current kubectl install will be removed in another ticket.

**Comment by guineveresaenger** [comment]
https://github.com/samsung-cnct/k2-tools/pull/29
