### ISSUE TITLE
include three versions of helm

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-tools#24]
as part of samsung-cnct/k2#222 we are now supporting three minor versions of kubernetes. to support this effort, this image will need to have three versions of helm installed at the following locations:

```
/opt/cnct/kubernetes/v1.4/bin/helm
/opt/cnct/kubernetes/v1.5/bin/helm
/opt/cnct/kubernetes/v1.6/bin/helm
```

helm is not versioned at the same time as kubectl so effort will be required to determine the correct version of helm to install at each location.

**Comment by coffeepac** [comment]
for backwards compatibility, the current helm install will be removed in another ticket.

**Comment by yenicapotediaz** [comment]
Here's my PR: https://github.com/samsung-cnct/k2-tools/pull/30

**Comment by coffeepac** [comment]
CAN"T @myself that's horrible.
