### ISSUE TITLE
Parallel file structure for kubectl and helm options

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2-tools#35]
Currently, the file path for kubectl-by-minor-version is set as 
`/opt/cnct/kubernetes/K8S_MINOR_VERSION/bin/kubectl`
and the one for helm as 
`/opt/cnct/kubernetes/K8S_MINOR_VERSION/bin/helm/helm`

and that doesn't make sense; kubectl and helm should either live in the same bin folder, or have each their own folders.

**Comment by coffeepac** [comment]
that's a weird one.  should be bin/helm not bin/helm/helm

**Comment by guineveresaenger** [comment]
Fixed it in the Dockerfile and did some refactory cleanup (we only need to build the version bins once, not twice).

**Comment by coffeepac** [comment]
ToReview:
 - make sure linked PR covers this ticket

**Comment by guineveresaenger** [comment]
^^ @coffeepac is that a reminder to yourself? or does it imply action on my part?

**Comment by coffeepac** [comment]
@guineveresaenger that is for whoever comes by to review this issue.  we shouldn't be self-reviewing tickets.
