### ISSUE TITLE
Uncomment helm version support for 1.6

### ISSUE THREAD

**Issue by yenicapotediaz** [samsung-cnct/k2-tools#41]
Now that there's a helm version supporting 1.6 the following lines should be uncommented.
Line 24: `#ENV     K8S_HELM_VERSION_1_6=v2.4.0`
Line 104: `#RUN     wget http://storage.googleapis.com/kubernetes-helm/helm-${K8S_HELM_VERSION_1_6}-linux-amd64.tar.gz && \`
Line 105: `#        tar -zxvf helm-${K8S_HELM_VERSION_1_6}-linux-amd64.tar.gz && mv linux-amd64/helm /opt/cnct/kubernetes/v1.6/bin/helm && rm -rf linux-amd64 helm-${K8S_HELM_VERSION_1_6}-linux-amd64.tar.gz`

Also, line 24 should be updated to v2.4.1 since that is now the latest.

**Comment by coffeepac** [comment]
this was completed, PR:  https://github.com/samsung-cnct/k2-tools/pull/44
