### ISSUE TITLE
Update ansible to 2.3.1

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2-tools#42]
There's a divide by 0 bug that's been fixed upstream. Upgrade ansible to 2.3.1 to fix the failure during a cluster down.

**Comment by DStorck** [comment]
went with 2.3.0.0 , as 2.3.1 was listed as a release-candidate on https://github.com/ansible/ansible/releases as of today

**Comment by joejulian** [comment]
The release cycle has slipped a little. 2.3.1 rc1 is 10 days old, rc2 should be released shortly and if no major bugs are found, the final release should be two days later. We should be able to complete this within the next sprint.

**Comment by coffeepac** [comment]
putting into blocked and kicking from board.  Will evaluate again later.

**Comment by joejulian** [comment]
This is not blocked as of today.

**Comment by DStorck** [comment]
should this be included in the weekly on-call version checks ? or do we want to be more deliberate about upgrading ansible? btw right now we are using ansible 2.3.0.0, which @joejulian said would fix the divide by 0 bug

**Comment by joejulian** [comment]
but it introduced a new bug (samsung-cnct/k2#434) that is fixed in 2.3.1

**Comment by joejulian** [comment]
Oh! and part of this update will require the new PR include a revert of #45

**Comment by davidewatson** [comment]
My gut feeling is that ansible should _not_ be part of the on-call check until if/when we have additional automation. Unlike k8s/helm, we don't really have a strong need to update immediately when there is a new release.

FWIW though, ansible security vulnerabilities exist: https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=ansible

**Comment by coffeepac** [comment]
upgrading ansible for any reason is really only for new features.  I am unconcerned with ansible CVEs.  The attack window that presents to consumers of K2 is probably nothing considering our usage (localhost only, user controlled execution).  Unless I'm missing an attack vector here?

**Comment by davidewatson** [comment]
I tend to agree, and actually wrote something similar before deciding check what kind of vulnerabilities Ansible has had. I think it's conceivable that we would care, but not any more than we care about the hundreds of other packages for which we rely on quay.io security scans.

**Comment by joejulian** [comment]
It may suit our use case, but CVE issues being reported by quay would still make for a poor public image.
![public image](https://i.imgflip.com/1q58da.jpg)

**Comment by joejulian** [comment]
It's been pointed out that my last comment lacked the necessary context to make it intelligible.

Quay checks for, and reports, CVE issues in images. If we leave known security vulnerabilities in our images just because we know that our use case will never hit them, it still is visible publicly that we have CVE issues in our images. This is bad for our reputation.

**Comment by davidewatson** [comment]
Right. I am adding a quay.io security check to the ok on call respkmsiblites...

**Comment by DStorck** [comment]
so after all this chatter, are we cool to move to 2.3.1? so people don't think k2 is held together with duct tape?

**Comment by DStorck** [comment]
done in https://github.com/samsung-cnct/k2-tools/pull/47

**Comment by joejulian** [comment]
LGTM. Tested successfully.
