### ISSUE TITLE
Optimize Dockerfile

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/k2-tools#51]
k2-tools is a big image and for people who are updating the image a lot, there might be ways to optimize the dockerfile, thus minimizing the amount that is downloaded

+ Migrate some commands to single lines ( `mkdir -p /opt/cnct/kubernetes/v1.4/bin && mkdir -p /opt/cnct/kubernetes/v1.5/bin && mkdir -p /opt/cnct/kubernetes/v1.6/bin` )
+ Push things that will change the least (directories that are created, old releases of kubectl, etc.) to the top of the Dockerfile, moving things that change the most to the bottom of the Dockerfile

**Comment by coffeepac** [comment]
this was done by a bunch of people.  it was a thing.
