### ISSUE TITLE
audit installed build tools

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-tools#60]
why do we have go, make and others installed in this image?  and why do they remain after the image is built.

**Comment by leahnp** [comment]
I think I will need go to stay to run the crash app. Unless there is a way around that?

**Comment by joejulian** [comment]
That'll be fixed with #61

**Comment by davidewatson** [comment]
I think this is a broader than just #61. @leahnp: We have existing golang build containers for careen and chaos-monkey. Ideally, we would consolidate on standard golang dev container. Whether that means taking functionality from careen and moving into k2-tools, or not, is an open question, methinks.

**Comment by coffeepac** [comment]
this work was completed and the larger issue @davidewatson brought up has been handled elsewhere.
