### ISSUE TITLE
Remove duplicated redundant repetitions.

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2-tools#66]
We've got a weird thing going now where a bunch of stuff is done first in the `Dockerfile` and then repeated in `imagerun.sh`.  Almost.  Almost exactly the same.

This is now a problem of making life really confusing for people.

**Comment by leahnp** [comment]
Can you explain how this ticket is blocking: https://github.com/samsung-cnct/k2/issues/574 @coffeepac ?

**Comment by coffeepac** [comment]
we want to remove the duplicate/confusing commands that exist in both the `Dockerfile` and `imagerun.sh` before adding anything else to the k2-tools image.

however, this ticket may have been resolved as part of the work that @joejulian did for fixing up the gcloud install [here](https://github.com/samsung-cnct/k2-tools/pull/89)
